name: alvin4c2m

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3:00 AM UTC
  workflow_dispatch:  # Enables manual triggering

jobs:
  merge_yaml_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Fetch and merge YAML files
      run: |
        # Define the URLs of the YAML files
        urls=(
          "https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/config.yaml"
          "https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/1/config.yaml"
          "https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/13/config.yaml"
          "https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/15/config.yaml"
          "https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/2/config.yaml"
          "https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/3/config.yaml"
        )

        # Initialize the final YAML file
        echo "# Combined alvin4c2m.yaml" > alvin4c2m.yaml

        # Loop through each URL, download the content, and append it to the final YAML file
        for url in "${urls[@]}"; do
          echo "Fetching $url ..."
          curl -sL "$url" >> alvin4c2m.yaml
          echo -e "\n" >> alvin4c2m.yaml  # Add spacing between the files
        done

    - name: Commit and push the combined YAML file
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add alvin4c2m.yaml
        git commit -m "Add combined alvin4c2m.yaml"
        git push
