name: "Alvin4c2m Workflow"

# Controls when the action will run: at 3:00 AM UTC and on manual dispatch
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  merge_yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y curl

    - name: Download and Merge YAML Files
      run: |
        # Download YAML files
        curl -o config.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/config.yaml
        curl -o config1.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/1/config.yaml
        curl -o config13.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/13/config.yaml
        curl -o config15.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/15/config.yaml
        curl -o config2.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/2/config.yaml
        curl -o config3.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/3/config.yaml

        # Merge YAML files into a single file
        echo "---" > alvin4c2m.yaml
        for file in config*.yaml; do
          echo "Merging $file into alvin4c2m.yaml"
          echo "---" >> alvin4c2m.yaml
          cat "$file" >> alvin4c2m.yaml
        done

    - name: Commit and push merged YAML file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add alvin4c2m.yaml
        git commit -m "Merged YAML files into alvin4c2m.yaml"
        git push
