name: Alvin4c2m Workflow

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 03:00 AM UTC
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  analyze-and-combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch and Combine YAML Files
        run: |
          # Create a folder to hold the YAML files
          mkdir -p clash_meta_files
          
          # Fetch the YAML files from the provided URLs
          curl -o clash_meta_files/config.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/config.yaml
          curl -o clash_meta_files/config1.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/1/config.yaml
          curl -o clash_meta_files/config13.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/13/config.yaml
          curl -o clash_meta_files/config15.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/15/config.yaml
          curl -o clash_meta_files/config2.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/2/config.yaml
          curl -o clash_meta_files/config3.yaml https://raw.githubusercontent.com/Alvin9999/pac2/refs/heads/master/clash.meta2/3/config.yaml

          # Combine the YAML files into one file
          echo "# Combined YAML from multiple sources" > alvin4c2m.yaml
          for file in clash_meta_files/*.yaml; do
            echo "\n# Contents from $file\n" >> alvin4c2m.yaml
            cat $file >> alvin4c2m.yaml
          done

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions@example.com"
          git config --local user.name "GitHub Actions"
          git add alvin4c2m.yaml
          git commit -m "Combine and parse clash.meta2 YAML files into alvin4c2m.yaml"
          git push
