name: Combine IPv6 Lists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Example: Runs daily at midnight UTC

jobs:
  combine:
    runs-on: ubuntu-latest # Run the job on an Ubuntu virtual machine

    steps:
      - uses: actions/checkout@v3 # Checkout the repository code

      - name: Download IPv6 Lists
        run: |
          curl -sSL "https://addressesapi.090227.xyz/cmcc-ipv6" >> ipv6collect2.txt
          curl -sSL "https://raw.githubusercontent.com/EzSync/test/main/ipv6-zamzhang.txt" >> ipv6collect2.txt
          curl -sSL "https://raw.githubusercontent.com/EzSync/test/main/ipv6collect1.txt" >> ipv6collect2.txt
          curl -sSL "https://raw.githubusercontent.com/EzSync/test/main/optipv6.txt" >> ipv6collect2.txt

      - name: Extract and save the IPv6 address
        run: |
          # Extract the last IPv6 address from the file
          ipv6_address=$(grep -oP '([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|::([0-9a-fA-F]{1,4}:){1,6}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::1|[0-9a-fA-F]{1,4}(:[0-9a-fA-F]{1,4}){0,7}:)' ipv6collect2.txt | tail -n 1
          echo "$ipv6_address" > ipv6collect2.txt

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add ipv6collect2.txt
          git commit -m "Save the latest IPv6 address"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use a secret for your personal access token
        run: git push origin main
