name: Fetch Valid IPs with Latency

on:
  # Allow manual triggering
  workflow_dispatch: {}
  # Schedule daily run at 8:00 PM PST
  schedule:
    - cron: '0 20 * * *'  # Every day at 20:00 (PST)

jobs:
  fetch-valid-ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear Existing Valid IPs
        run: rm -f validips-amtun.txt

      - name: Create tmp directory
        run: mkdir -p tmp

      - name: Download IP/Domain List
        run: curl -sSL https://raw.githubusercontent.com/amclubs/am-cf-tunnel/main/ipv4.txt -o tmp/ips.txt

      - name: Measure Latency and Filter Valid Entries
        run: |
          cat tmp/ips.txt | grep -Ev '^$' | while read -r ip; do
            latency=$(curl -sSL -w "%{time_connect}\n" -o /dev/null https://www.google.com/generate_204 -H "Host: $ip" 2>/dev/null)
            if [[ $(echo "$latency > 0 && $latency < 0.5" | bc -l) -eq 1 ]]; then
              echo "$ip" >> validips-amtun.txt
            fi
          done
