name: Fetch Valid IPs with Latency

on:
  # Allow manual triggering
  workflow_dispatch: {}
  # Schedule daily run at 8:00 PM PST
  schedule:
    - cron: '0 20 * * *'  # Every day at 20:00 (PST)

jobs:
  fetch-valid-ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear Existing Valid IPs
        run: rm -f validips-amtun.txt

      - name: Download IP/Domain List
        uses: actions/download-artifact@v3  # Use official action for downloads
        with:
          name: ip-list  # Optional: Use a consistent name for the artifact
          path: tmp/ips.txt

      - name: Measure Latency and Filter Valid Entries
        run: |
          cat tmp/ips.txt | grep -Ev '^$' | while read -r ip; do
            latency=$(curl -sSL -w "%{http_code}\n" -o /dev/null https://www.google.com/generate_204 -H "Host: $ip" | grep -Eo '[0-9]+')
            if [[ $latency -gt 0 && $latency -lt 500 ]]; then
              echo "$ip" >> validips-amtun.txt
            fi
          done
