name: Get Valid IPs

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 20 * * *' # Runs at 20:00 PM every day

jobs:
  get_valid_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear contents of validips-amtun.txt
        run: |
          echo "" > validips-amtun.txt

      - name: Fetch IPs and Domains from URL
        run: |
          curl -s https://raw.githubusercontent.com/amclubs/am-cf-tunnel/main/ipv4.txt -o ips_and_domains.txt

      - name: Test Accessibility of IPs and Domains
        run: |
          while IFS= read -r entry; do
            if curl -s --head --request GET "$entry" | grep "200 OK" > /dev/null; then
              echo "$entry" >> validips-amtun.txt
            fi
          done < ips_and_domains.txt

      - name: Display valid IPs and Domains
        run: |
          echo "Valid IPs and Domains:"
          cat validips-amtun.txt
