name: Fetch Valid IPs with Latency

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 20 * * *'

jobs:
  fetch-valid-ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear Existing Valid IPs
        run: rm -f validips-amtun.txt

      - name: Create tmp directory
        run: mkdir -p tmp

      - name: Download IP/Domain List
        run: curl -sSL https://raw.githubusercontent.com/amclubs/am-cf-tunnel/main/ipv4.txt -o tmp/ips.txt

      - name: Measure Latency and Filter Valid Entries
        run: |
          cat tmp/ips.txt | grep -Ev '^$' | while read -r ip; do
            latency_seconds=$(curl -sSL -w "%{time_connect}\n" -o /dev/null https://www.google.com/generate_204 -H "Host: $ip" 2>/dev/null)
            if [[ -n "$latency_seconds" ]]; then # Check if latency measurement was successful
                latency_ms=$(echo "scale=3; $latency_seconds * 1000" | bc)
                if (( $(echo "$latency_ms > 0 && $latency_ms < 500" | bc -l) )); then
                  echo "$ip" >> validips-amtun.txt
                fi
            fi
          done
      - name: Display content of validips-amtun.txt
        run: cat validips-amtun.txt
