name: Get Valid IPs

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 20 * * *' # Runs at 20:00 PM every day

jobs:
  get_valid_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear contents of validips-amtun.txt
        run: |
          echo "" > validips-amtun.txt

      - name: Fetch IPs from URL
        run: |
          curl -s https://raw.githubusercontent.com/amclubs/am-cf-tunnel/main/ipv4.txt -o ips.txt

      - name: Test Latency of IPs
        run: |
          while IFS= read -r ip; do
            # Measure latency by sending a request to the Google endpoint
            latency=$(curl -o /dev/null -s -w "%{time_total}\n" --connect-timeout 5 --resolve "$ip:80:www.google.com" https://www.google.com/generate_204)
            if [ -n "$latency" ] && (( $(echo "$latency > 0" | bc -l) )) && (( $(echo "$latency < 0.5" | bc -l) )); then
              echo "$ip - Latency: $latency seconds" >> validips-amtun.txt
            fi
          done < ips.txt

      - name: Display valid IPs and Latencies
        run: |
          echo "Valid IPs with Latency greater than 0 ms and less than 500 ms:"
          cat validips-amtun.txt
