name: Fetch and Validate IPs

on:
  schedule:
    - cron: '0 20 * * *' # Runs daily at 20:00 (8:00 PM) UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-validate-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear valid IPs file
        run: echo "" > validips-amtun.txt

      - name: Fetch IPs and Domains
        run: curl -o ips.txt https://raw.githubusercontent.com/amclubs/am-cf-tunnel/main/ipv4.txt

      - name: Validate IPs and Domains
        run: |
          while IFS= read -r ip
          do
            # Measure latency by sending a request to the Google endpoint
            latency=$(curl -o /dev/null -s -w "%{time_total}\n" --connect-timeout 5 --resolve "$ip:80:www.google.com" https://www.google.com/generate_204)
            # Check if latency is greater than 0 and less than 500 ms (0.5 seconds)
            if [[ $(echo "$latency > 0 && $latency < 0.5" | bc -l) -eq 1 ]]
            then
              echo "$ip - Latency: $latency seconds" >> validips-amtun.txt
            fi
          done < ips.txt
