name: Get Valid IPs

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 20 * * *' # Runs at 20:00 PM every day

jobs:
  get_valid_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear contents of validips-amtun.txt
        run: |
          echo "" > validips-amtun.txt

      - name: Fetch IPs from URL
        run: |
          curl -s https://raw.githubusercontent.com/amclubs/am-cf-tunnel/main/ipv4.txt -o ips.txt

      - name: Ping IPs and save valid ones
        run: |
          while IFS= read -r ip; do
            if ping -c 1 "$ip" &> /dev/null; then
              echo "$ip" >> validips-amtun.txt
            fi
          done < ips.txt

      - name: Display valid IPs
        run: |
          echo "Valid IPs:"
          cat validips-amtun.txt
