name: Update IP List

on:
  schedule:
    - cron: '0 0 * * *'  # Update daily at midnight (change as needed)
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download IP list
        run: |
          curl -sL https://github.com/amclubs/am-cf-tunnel/blob/main/ipv4.txt > ips-amtunnel.txt

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.email "you@example.com"  # Replace with your email
          git config --global user.name "GitHub Actions"
          OLD_CONTENT=$(git show HEAD:ips-amtunnel.txt | tr '\n' ' ')
          NEW_CONTENT=$(cat ips-amtunnel.txt | tr '\n' ' ')
          if [[ "$OLD_CONTENT" != "$NEW_CONTENT" ]]; then
            echo "Content changed!"
            exit 1
          else
            echo "Content hasn't changed."
            exit 0
          fi

      - name: Add comment to Cloudflare entries (if content changed)
        run: |
          if [[ $? -eq 1 ]]; then  # Only run if content changed (check_changes exit code)
            sed -i 's/\.ns\.cloudflare\.com/\.ns\.cloudflare\.com #ns\.cloudflare/g' ips-amtunnel.txt
          fi

      - name: Commit changes (if content changed)
        run: |
          if [[ $? -eq 1 ]]; then  # Only run if content changed (check_changes exit code)
            git add ips-amtunnel.txt
            git commit -m "Update IP list from URL"
            git push origin HEAD
          fi
