name: Update IPv6 Collect with Webpage Change

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  update_ipv6_collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Fetch and extract IPv6 addresses
        id: fetch_ips
        run: |
          # Define the URLs to monitor
          URL1="https://monitor.gacjie.cn/page/cloudflare/ipv6.html"
          URL2="https://stock.hostmonit.com/CloudFlareYesV6"
          
          # Fetch the current content of the pages
          CONTENT1=$(curl -s "$URL1")
          CONTENT2=$(curl -s "$URL2")

          # Debug: Print the fetched content from both URLs
          echo "Fetched Content from URL1:"
          echo "$CONTENT1"
          echo "Fetched Content from URL2:"
          echo "$CONTENT2"

          # Extract IPv6 addresses using a simplified regex from both contents
          IPV6_ADDRESSES1=$(echo "$CONTENT1" | grep -oP '([0-9a-fA-F]{1,4}:){1,7}[0-9a-fA-F]{1,4}' | sort -u)
          IPV6_ADDRESSES2=$(echo "$CONTENT2" | grep -oP '([0-9a-fA-F]{1,4}:){1,7}[0-9a-fA-F]{1,4}' | sort -u)

          # Combine the extracted IPv6 addresses from both sources
          ALL_IPV6_ADDRESSES=$(echo -e "$IPV6_ADDRESSES1\n$IPV6_ADDRESSES2" | sort -u)

          # Debug: Print the combined IPv6 addresses
          echo "Combined Extracted IPv6 Addresses:"
          echo "$ALL_IPV6_ADDRESSES"

          # Replace the contents of ipv6collect.txt with the new IPs
          echo "$ALL_IPV6_ADDRESSES" > ipv6collect.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv6collect.txt
          git commit -m "Update ipv6collect.txt with new IPv6 addresses" || echo "No changes to commit"
          git push
