name: Collect IPv6 Addresses

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_ipv6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Fetch and process IPv6 addresses
        run: |
          import requests
          from bs4 import BeautifulSoup

          # Fetch the webpage
          url = 'https://stock.hostmonit.com/CloudFlareYesV6'
          response = requests.get(url)
          soup = BeautifulSoup(response.text, 'html.parser')

          # Extract IPv6 addresses from the table
          ipv6_addresses = []
          for row in soup.select('tr.el-table__row'):
              ip_cell = row.select_one('td.el-table_1_column_2 .cell')
              if ip_cell:
                  ipv6_addresses.append(f"[{ip_cell.text.strip()}]")

          # Remove duplicates while preserving order
          unique_ipv6_addresses = list(dict.fromkeys(ipv6_addresses))

          # Write to file
          with open('ipv6collect2.txt', 'w') as f:
              f.write('\n'.join(unique_ipv6_addresses))

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv6collect2.txt
          git commit -m "Update IPv6 addresses" || echo "No changes to commit"
          git push
