name: IPV6Collect No.3

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:
  push:
  watch:
    paths:
      - 'https://stock.hostmonit.com/CloudFlareYesV6'

jobs:

  collect_ipv6:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: EzSync/test
        
    - name: Analyze IPV6 format
      run: |
        # Use a tool like BeautifulSoup or Scrapy to parse the HTML
        # and identify the format of the IPV6 addresses
        ipv6_format="(?:[0-9A-F]{1,4}:){7}[0-9A-F]{1,4}"
        
    - name: Fetch IPV6 addresses
      run: |
        # Use a web scraping library to fetch the IPV6 addresses
        # from the webpage using the identified format
        import requests
        from bs4 import BeautifulSoup
        
        url = "https://stock.hostmonit.com/CloudFlareYesV6"
        response = requests.get(url)
        soup = BeautifulSoup(response.text, "html.parser")
        
        ipv6_addresses = re.findall(ipv6_format, soup.text)
        
        # Write the IPV6 addresses to a file
        with open("ipv6collect2.txt", "w") as f:
            f.write("\n".join(ipv6_addresses))
            
    - name: Remove duplicates
      run: |
        # Remove any duplicate IPV6 addresses from the file
        with open("ipv6collect2.txt", "r") as f:
            ipv6_addresses = set(f.read().splitlines())
        
        with open("ipv6collect2.txt", "w") as f:
            f.write("\n".join(ipv6_addresses))
            
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Update IPV6 addresses'
        add: '*.txt'
