name: IPv6 Address Collector No.2

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_ipv6_addresses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch webpage
        run: |
          # Fetch the webpage and output the raw HTML for debugging
          curl -s https://stock.hostmonit.com/CloudFlareYesV6 -o webpage.html
          echo "Raw HTML content:"
          cat webpage.html  # Output the raw HTML content for debugging

      - name: Extract relevant section
        run: |
          # Extract the relevant section of the HTML for debugging
          cat webpage.html | grep -A 20 '<col name="el-table_1_column_2"' > relevant_section.html
          echo "Relevant section of HTML:"
          cat relevant_section.html

      - name: Extract IPv6 addresses
        run: |
          # Extract IPv6 addresses from the second occurrence of the column
          awk -F'<td' '/el-table_1_column_2/{count++} count==2 {print $2}' relevant_section.html | \
          grep -oP '[0-9a-fA-F:]{2,}' | sed 's/^/[/; s/$/]/' > ipv6_addresses.txt || echo "No IPv6 addresses found."

          # Debugging: Check the contents of ipv6_addresses.txt
          echo "Extracted IPv6 addresses:"
          cat ipv6_addresses.txt

      - name: Update ipv6collect2.txt
        run: |
          # Remove duplicates and write to ipv6collect2.txt
          sort -u ipv6_addresses.txt > ipv6collect2.txt
          echo "Updated ipv6collect2.txt with unique IPv6 addresses."

      - name: Check for changes
        run: |
          # Check if ipv6collect2.txt has changed
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code ipv6collect2.txt || (git commit -am "Update ipv6collect2.txt with new IPv6 addresses" && git push)
