name: IPv6 Address Collector No.1

on:
  schedule:
    - cron: '10 6-22 * * *'  # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_ipv6_addresses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch IPv6 addresses
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y curl jq

          # Fetch the webpage and extract IPv6 addresses
          curl -s https://monitor.gacjie.cn/page/cloudflare/ipv6.html | \
          grep -oE '([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]|[1-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]|[1-9]){0,1}[0-9])' | \
          sort -u > new_ipv6collect1.txt

      - name: Enclose IPv6 addresses in brackets
        run: |
          # Enclose each IPv6 address in square brackets
          sed -i 's/^/[/' new_ipv6collect1.txt
          sed -i 's/$/]/' new_ipv6collect1.txt

      - name: Append new addresses to ipv6collect1.txt
        run: |
          # Append new addresses to ipv6collect1.txt
          cat new_ipv6collect1.txt >> ipv6collect1.txt

      - name: Sort and remove duplicates from ipv6collect1.txt
        run: |
          # Sort the file and remove duplicates
          sort -u ipv6collect1.txt -o ipv6collect1.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv6collect1.txt
          git commit -m "Append new IPv6 addresses to ipv6collect1.txt and remove duplicates" || echo "No changes to commit"
          git push
