name: IPv6 Address Collector No.2

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_ipv6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can specify the version you need

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Fetch IPv6 addresses
        run: |
          echo "const puppeteer = require('puppeteer');" > fetch.js
          echo "async function run() {" >> fetch.js
          echo "  const browser = await puppeteer.launch();" >> fetch.js
          echo "  const page = await browser.newPage();" >> fetch.js
          echo "  await page.goto('https://stock.hostmonit.com/CloudFlareYesV6');" >> fetch.js
          echo "  const ipv6s = await page.evaluate(() => {" >> fetch.js
          echo "    return Array.from(document.querySelectorAll('div.cell')).map(div => div.innerText).filter(text => text.match(/([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}/));" >> fetch.js
          echo "  });" >> fetch.js
          echo "  console.log(ipv6s);" >> fetch.js
          echo "  require('fs').writeFileSync('ipv6collect2.txt', ipv6s.map(ip => '[' + ip + ']').join('\\n'));" >> fetch.js
          echo "  await browser.close();" >> fetch.js
          echo "}" >> fetch.js
          echo "run();" >> fetch.js
          node fetch.js

      - name: Remove duplicates
        run: |
          # Remove duplicates while preserving order
          awk '!seen[$0]++' ipv6collect2.txt > temp.txt && mv temp.txt ipv6collect2.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv6collect2.txt
          git commit -m "Update IPv6 addresses" || echo "No changes to commit"
          git push
