name: Merge IPv6 Addresses

on:
  schedule:
    - cron: '0 21 * * *' # This is 5:00 AM Beijing time (UTC+8) in UTC time
  workflow_dispatch:

jobs:
  merge_ipv6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch and merge IPv6 addresses
        run: |
          # Create or clear the ipv6-merge.txt file
          > ipv6-merge.txt
          
          # Fetch contents from the URLs and append to ipv6-merge.txt
          for url in \
            "https://addressesapi.090227.xyz/cmcc-ipv6" \
            "https://raw.githubusercontent.com/EzSync/test/main/ipv6-zamzhang.txt" \
            "https://raw.githubusercontent.com/EzSync/test/main/ipv6collect1.txt" \
            "https://raw.githubusercontent.com/EzSync/test/main/optipv6.txt"; do
              echo "Fetching $url"
              curl -s "$url" >> ipv6-merge.txt
          done

      - name: Sort and remove duplicates
        run: |
          sort -u ipv6-merge.txt -o ipv6-merge.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv6-merge.txt
          git commit -m "Update ipv6-merge.txt with merged and sorted IPv6 addresses" || echo "No changes to commit"
          git push
