name: Merge IPv6 Addresses

on:
  schedule:
    - cron: '0 21 * * *' # This is 5:00 AM Beijing time (UTC+8) in UTC time
  workflow_dispatch:

jobs:
  merge_ipv6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch IPv6 addresses
        run: |
          for url in \
            "https://addressesapi.090227.xyz/cmcc-ipv6" \
            "https://raw.githubusercontent.com/EzSync/test/main/ipv6collect1.txt" \
            "https://raw.githubusercontent.com/EzSync/test/main/optipv6.txt"; do
              echo "Fetching $url"
              response=$(curl -s -w "%{http_code}" -o temp.txt -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" -L "$url")
              if [ "$response" -eq 200 ]; then
                cat temp.txt >> ipv6-merge.txt
              else
                echo "Error fetching $url: HTTP status $response"
              fi
          done
          rm temp.txt

      - name: Sort and remove duplicates
        run: |
          sort -u ipv6-merge.txt -o ipv6-merge.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv6-merge.txt
          git commit -m "Update ipv6-merge.txt with merged and sorted IPv6 addresses" || echo "No changes to commit"
          git push
