name: IPv6 Merge Workflow

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  push:
  

jobs:
  update_ipv6_addresses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check and Enclose Lines in Brackets
        run: |
          FILE="text/ipv6collect.txt"
          if [ -f "$FILE" ]; then
            sed -i -E 's/^([^[])(.*)$/[&]/' "$FILE"  # Enclose lines not in brackets
          fi

      - name: Fetch IPv6 Addresses
        run: |
          curl -s https://monitor.gacjie.cn/page/cloudflare/ipv6.html | \
          grep -oP '([0-9a-fA-F:]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F:]{1,4}:){1,7}:|([0-9a-fA-F:]{1,6}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F:]{1,5}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F:]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F:]{1,3}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F:]{1,2}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F:]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)' | \
          sed 's/^/[/' | sed 's/$/]/' >> "$FILE"

      - name: Remove Duplicates
        run: |
          awk '!seen[$0]++' "$FILE" > temp && mv temp "$FILE"

      - name: Sort IPv6 Addresses
        run: |
          sort -u "$FILE" -o "$FILE"
