name: IPV6 Address Collector No.3

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:
  push:
  watch:
    paths:
      - 'https://stock.hostmonit.com/CloudFlareYesV6'

jobs:

  collect_ipv6:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: EzSync/test
        
    - name: Fetch IPV6 addresses
      run: |
        # Use curl to fetch the HTML content of the webpage
        curl -s https://stock.hostmonit.com/CloudFlareYesV6 | \
        # Use grep to extract the IPV6 addresses
        grep -oE '([0-9A-F]{1,4}:){7}[0-9A-F]{1,4}' > ipv6collect2.txt
        
    - name: Remove duplicates
      run: |
        # Remove any duplicate IPV6 addresses from the file
        sort -u ipv6collect2.txt -o ipv6collect2.txt
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Update IPV6 addresses'
        add: '*.txt'
