name: IPv6_zamzhang

on:
  schedule:
    - cron: '15 17 * * *'  # Runs every day at 01:00 BJT/17:15 UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-ipv6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch content from URL
        id: fetch_content
        run: |
          # Fetch the content from the URL and output it for debugging
          curl -s https://raw.githubusercontent.com/zamzhang/ip/main/ip1.txt > ip_content.txt
          cat ip_content.txt  # Output the content for debugging

      - name: Extract and process IPv6 addresses
        run: |
          # Extract IPv6 addresses enclosed in brackets
          grep -oP '\[[0-9a-fA-F:]+\]' ip_content.txt | \
          sort -u > ipv6-zamzhang.txt

      - name: Check file content
        run: |
          cat ipv6-zamzhang.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv6-zamzhang.txt
          git commit -m "Update ipv6-zamzhang.txt with new IPv6 addresses" || echo "No changes to commit"
          git push
