name: Update IPv6 Addresses Manually

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_ipv6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Install required tools
        run: |
          sudo apt update
          sudo apt install jq curl

      - name: Fetch IPv6 addresses
        id: fetch_ipv6
        run: |
          curl 'https://stock.hostmonit.com/CloudFlareYesV6' | 
          grep -o '(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){5}:([0-9a-fA-F]{1,4}:){2}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){4}:([0-9a-fA-F]{1,4}:){3}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){3}:([0-9a-fA-F]{1,4}:){4}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){2}:([0-9a-fA-F]{1,4}:){5}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1}:([0-9a-fA-F]{1,4}:){6}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){0}:([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4})' |
          jq -r '.[]' > ipv6_addresses.txt

      - name: Update ipv6collect2.txt
        run: |
          cp ipv6_addresses.txt ipv6collect2.txt

      - name: Remove duplicates
        run: |
          awk '!seen[$0]++' ipv6collect2.txt > ipv6collect2.tmp && mv ipv6collect2.tmp ipv6collect2.txt

      - name: Commit changes (if any)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add ipv6collect2.txt
          git commit -m "Update IPv6 addresses from 'https://stock.hostmonit.com/CloudFlareYesV6'" || true

      - name: Push changes (if any)
        run: |
          git push origin master
