name: IPv6 Address Collector No.2

on:
  schedule:
    - cron: '15 6-22/1 * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  fetch-ipv6:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        
    - name: Fetch IPv6 Addresses
      run: |
        python fetch_ipv6.py
        
    - name: Commit and Push Changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        directory: .
        message: "Update IPv6 Addresses"
