name: Check for Duplicates

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  check_duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for duplicate lines
        id: check_duplicates
        run: |
          # Read the file and remove duplicates
          sort -u optdoms.txt -o optdoms.txt
          
          # Check if the file has changed
          if ! git diff --quiet; then
            echo "Duplicates found and removed. Updating the file."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add optdoms.txt
            git commit -m "Remove duplicate lines from optdoms.txt"
            git push
          else
            echo "No duplicates found."
          fi
