name: Maintain IPv6 File

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:
  push:

jobs:
  update-ipv6-file:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'EzSync/test'  # Replace with your GitHub username and repository name
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Update IPv6 file
      env:
        FILE_PATH: 'optipv6.txt'
      run: |
        import os
        import re
        from datetime import datetime

        file_path = os.environ['FILE_PATH']

        def check_and_update_ipv6_file():
            # Read the contents of the file
            with open(file_path, "r") as file:
                ipv6_addresses = [line.strip() for line in file.readlines()]

            # Check if each IPv6 address is enclosed in []
            updated_addresses = []
            for address in ipv6_addresses:
                if not address.startswith("[") or not address.endswith("]"):
                    address = f"[{address}]"
                updated_addresses.append(address)

            # Remove duplicate IPv6 addresses
            unique_addresses = list(set(updated_addresses))

            # Update the file with the cleaned up and unique IPv6 addresses
            with open(file_path, "w") as file:
                file.write("\n".join(unique_addresses))

            print(f"IPv6 file updated at {datetime.now()}")

        check_and_update_ipv6_file()
      
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update IPv6 file
        branch: ${{ github.head_ref }}
