import os
import re
from datetime import datetime

# Set the path to the "optipv6.txt" file
file_path = "optipv6.txt"

def check_and_update_ipv6_file():
    # Read the contents of the file
    with open(file_path, "r") as file:
        ipv6_addresses = file.readlines()

    # Check if each IPv6 address is enclosed in []
    updated_addresses = []
    for address in ipv6_addresses:
        address = address.strip()
        if not address.startswith("[") or not address.endswith("]"):
            address = f"[{address}]"
        updated_addresses.append(address)

    # Remove duplicate IPv6 addresses
    unique_addresses = list(set(updated_addresses))

    # Update the file with the cleaned up and unique IPv6 addresses
    with open(file_path, "w") as file:
        file.write("\n".join(unique_addresses))

    print(f"IPv6 file updated at {datetime.now()}")

# Run the check and update function every 10 minutes
while True:
    check_and_update_ipv6_file()
    os.system("sleep 600")  # Wait for 10 minutes
