name: RM DomDups onChange

on:
  push:
    paths:
      - optdoms.txt  # Trigger the workflow when optdoms.txt changes

jobs:
  check_duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append #OptDom to lines without #
        run: |
          # Append #OptDom to lines that do not contain #
          awk '!/#/' optdoms.txt | sed 's/$/#OptDom/' >> temp.txt
          awk '/#/' optdoms.txt >> temp.txt
          mv temp.txt optdoms.txt

      - name: Check for duplicate lines
        id: check_duplicates
        run: |
          # Read the file and remove duplicates
          sort -u optdoms.txt -o optdoms.txt
          
          # Check if the file has changed
          if ! git diff --quiet; then
            echo "Duplicates found and removed. Updating the file."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add optdoms.txt
            git commit -m "Remove duplicate lines from optdoms.txt and append #OptDom"
            git push
          else
            echo "No duplicates found."
          fi
