name: RM DomDups onChange

on:
  push:
    paths:
      - optdoms.txt  # Trigger the workflow when optdoms.txt changes

jobs:
  check_duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for duplicate lines and add '#OptDom'
        id: check_duplicates
        run: |
          # Add '#OptDom' to lines not containing '#'
          awk '/^#/{print} !/#/{print; print "#OptDom"}' optdoms.txt > tmp_optdoms.txt

          # Sort and remove duplicates
          sort -u tmp_optdoms.txt > optdoms.txt

          # Check if the file has changed
          if ! git diff --quiet; then
            echo "Duplicates found and removed. Updating the file with '#OptDom'."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add optdoms.txt
            git commit -m "Remove duplicate lines and add '#OptDom' to optdoms.txt"
            git push
          else
            echo "No duplicates found."
          fi

          # Clean up temporary file
          rm tmp_optdoms.txt
