name: IPv6 File Check Workflow

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  check_optipv6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check and Enclose Lines in Brackets
        run: |
          FILE="text/optipv6.txt"
          if [ -f "$FILE" ]; then
            # Enclose lines not in brackets
            sed -i -E 's/^([^[])(.*)$/[&]/' "$FILE"
          else
            echo "File $FILE does not exist."
            exit 1
          fi

      - name: Remove Duplicates
        run: |
          FILE="text/optipv6.txt"
          if [ -f "$FILE" ]; then
            awk '!seen[$0]++' "$FILE" > temp && mv temp "$FILE"
          else
            echo "File $FILE does not exist."
            exit 1
          fi

      - name: Sort Lines
        run: |
          FILE="text/optipv6.txt"
          if [ -f "$FILE" ]; then
            sort -u "$FILE" -o "$FILE"
          else
            echo "File $FILE does not exist."
            exit 1
          fi
