name: RepCheck for Duplicates on Change

on:
  push:
    paths:
      - optipv6.txt  # Trigger the workflow when optipv6.txt changes

jobs:
  check_duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for duplicate lines
        id: check_duplicates
        run: |
          # Read the file and remove duplicates
          sort -u optipv6.txt -o optipv6.txt
          
          # Check if the file has changed
          if ! git diff --quiet; then
            echo "Duplicates found and removed. Updating the file."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add optipv6.txt
            git commit -m "Remove duplicate lines from optipv6.txt"
            git push
          else
            echo "No duplicates found."
          fi
