name: IPv6 File Check Workflow

on:
  push:
    paths:
      - 'test/optipv6.txt'  # Trigger the workflow when this file changes

jobs:
  check_optipv6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Enclose Lines in Brackets
        run: |
          FILE="test/optipv6.txt"
          if [ -f "$FILE" ]; then
            # Create a new file with lines enclosed in brackets
            while IFS= read -r line; do
              # Check if the line is already enclosed in brackets
              if [[ ! "$line" =~ ^\[.*\]$ ]]; then
                echo "[$line]" >> temp.txt
              else
                echo "$line" >> temp.txt
              fi
            done < "$FILE"
            mv temp.txt "$FILE"
          else
            echo "File $FILE does not exist."
            exit 1
          fi

      - name: Remove Duplicates
        run: |
          FILE="test/optipv6.txt"
          if [ -f "$FILE" ]; then
            # Remove duplicates and save to a temporary file
            sort -u "$FILE" -o "$FILE"
          else
            echo "File $FILE does not exist."
            exit 1
          fi

      - name: Sort Lines
        run: |
          FILE="test/optipv6.txt"
          if [ -f "$FILE" ]; then
            # Sort the lines and save back to the original file
            sort -o "$FILE" "$FILE"
          else
            echo "File $FILE does not exist."
            exit 1
          fi
