name: Update IPv4 Collect with Webpage Change

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  push:

jobs:
  update_ipv4_collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Fetch and extract IPv4 addresses
        id: fetch_ips
        run: |
          # Define the URLs to monitor
          URL1="https://monitor.gacjie.cn/page/cloudflare/ipv4.html"
          URL2="https://ip.164746.xyz/"
          
          # Fetch the current content of the pages
          CONTENT1=$(curl -s $URL1)
          CONTENT2=$(curl -s $URL2)

          # Extract IPv4 addresses using grep and regex
          IP_ADDRESSES1=$(echo "$CONTENT1" | grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b')
          IP_ADDRESSES2=$(echo "$CONTENT2" | grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b')

          # Combine the IP addresses
          ALL_IP_ADDRESSES=$(echo -e "$IP_ADDRESSES1\n$IP_ADDRESSES2")

          # Append new IPs to ipv4collect.txt
          echo "$ALL_IP_ADDRESSES" >> ipv4collect.txt

      - name: Remove duplicates and sort IPs
        run: |
          # Check if the ipv4collect.txt file exists
          if [ -f "ipv4collect.txt" ]; then
            # Remove duplicates and sort the file
            sort -u ipv4collect.txt -o ipv4collect.txt
          else
            echo "ipv4collect.txt does not exist."
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv4collect.txt
          git commit -m "Update ipv4collect.txt with new IP addresses" || echo "No changes to commit"
          git push
